### ISSUE TITLE
Sometimes headers options required to be customized

### ISSUE THREAD

**Issue by blasvicco** [ostark/upper#16]
For particular cases like our cache settings, the Client request need from us to set the proper `HOST` attribute to the headers in order to specifies the correct domain name of the server.

**Comment by funnylookinhat** [comment]
@ostark This isn't the case for every Varnish deployment, but oftentimes varnish can be configured to either cache more than one domain OR it is behind a load balancer (so that requests hitting the varnish box are routed to an internal hostname or IP rather than directly to your public domain).  We're the latter case, which is why to properly do a purge call you need to add a `Host: foo.com` header.

Our VCL isn't anything special when it comes to the purge section - here's what we've got in `vcl_recv`:

```
sub vcl_recv {
  // We skip all of our rules if a purge is called.
  if (req.method == "PURGE") {
    return(purge);
  }
  /* ... */
}
```
